# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: photomap-server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  package_individually:
    dev: false
    prod: true
  apigwBinary:
    types:
      - 'multipart/form-data'
      - 'image/png'
      - 'image/jpeg'
      - 'image/bmp'
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules:
      forceInclude:
        - serverless-http
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    tableThroughputs:
      prod: 10
      default: 1
    tableThroughput: ${self:custom.dynamodb.tableThroughputs.${env:STAGE}, self:custom.dynamodb.tableThroughputs.default}
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
  customDomain:
    domainName: soybeans.tech
    basePath: ${env:BASE_PATH}
    stage: ${env:STAGE}
    certificateName: 'soybeans.tech'
    createRoute53Record: true

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: ap-northeast-2
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutelementryRecords'
      Resource:
        - '*'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::photomap/*'
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'arn:aws:dynamodb:ap-northeast-2:*:*'

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1
package:
  individually: ${self:custom.package_individually.${env:STAGE}, false}

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  # 기본 테스트용 함수
  hello:
    handler: index.handler
    tracing: true
    events:
      - http:
          path: /hello
          method: get
  # 인증 관련 함수
  authorize:
    handler: src/auth.verify
    tracing: true
  refresh:
    handler: src/auth.refresh
    tracing: true
    events:
      - http:
          path: /refresh
          method: get
          authorizer: authorize
  # 유저 관련 함수
  User:
    handler: src/users.handler
    tracing: true
    events:
      - http:
          path: /users
          method: ANY
          authorizer: authorize
  # 지도 관련 함수
  Map:
    handler: src/maps.handler
    tracing: true
    events:
      - http:
          path: /maps
          method: ANY
          authorizer: authorize
      - http:
          path: /maps/{any+}
          method: ANY
          authorizer: authorize
  # 스토리 관련 함수
  Story:
    handler: src/stories.handler
    tracing: true
    events:
      - http:
          path: /stories
          method: ANY
          authorizer: authorize
      - http:
          path: /stories/{any+}
          method: ANY
          authorizer: authorize
  # 푸시 관련 함수
  Push:
    handler: src/push.handler
    tracing: true
    events:
      - http:
          path: /push
          method: ANY
          authorizer: authorize
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

plugins:
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-plugin-tracing
  - serverless-domain-manager
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/api-gateway.yml)}
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
