Resources:
  photoMapTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:DYNAMODB_TABLE}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: types
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.dynamodb.tableThroughput}
        WriteCapacityUnits: ${self:custom.dynamodb.tableThroughput}
      # Global Secondary Index
      GlobalSecondaryIndexes:
        - IndexName: GSI
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: types
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.dynamodb.tableThroughput}
            WriteCapacityUnits: ${self:custom.dynamodb.tableThroughput}
  noticeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: noticeTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
